[package]
name = "xtended-collections"
version = "0.0.3"
description = "Extended collections library for Motoko including dynamic arrays and other data structures"
repository = "https://github.com/edjcase/motoko_collections"
keywords = ["buffer", "dynamic", "array", "vector", "list"]
license = "Apache-2.0"

[dependencies]
core = "0.6.0"
buffer = "0.0.1"

[dev-dependencies]
test = "2.1.1"
